---
services:
  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend-service:/app
  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy:/etc/nginx/conf.d
    depends_on:
      - backend-service